name: Updato CDN
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: NellowTCS/updato@1.0.1
        with:
          mode: version
          dist_dir: Build/dist
          build_script: cd Build && npm ci && npm run build
